name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.ts'
      - 'package.json'

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - run: npm run lint
      - run: npm run test:coverage
